### ISSUE TITLE
Create devstack image builders for Olive release

### ISSUE THREAD

**Issue by jmbowman** [openedx-unsupported/devstack#1000]
Now that Olive has been released, we need to make sure we're building devstack images for it; Tutor is the recommended development environment, but some things like certain MFEs still work better in devstack.

A/C:

* File an SRE issue to create the image builders.  For reference the one for Nutmeg was https://2u-internal.atlassian.net/browse/PSRE-1817 .
* Once the jobs have been created, make sure that they run successfully and upload Olive-tagged images to Docker Hub.
* Determine if any services had already switched to Ansible-free images built by a GitHub Action, and if so make sure that appropriately-tagged images are built from the correct branch.
* Verify that a working devstack can be created for Olive once all the images are available.

**Comment by dyudyunov** [comment]
Are there any updates?

**Comment by jmbowman** [comment]
It's now at the top of the team's backlog, it's been waiting behind wrap-up of already-started projects and a few fixes for minor security risks.

**Comment by aht007** [comment]
Made SRE ticket for creating Olive Image builders. https://2u-internal.atlassian.net/servicedesk/customer/portal/15/DOS-3554

**Comment by iamsobanjaved** [comment]
Issue resolved in https://2u-internal.atlassian.net/browse/PSRE-2180

**Comment by dyudyunov** [comment]
@iamsobanjaved Am I right that all the ACs from the issue description are done?

I need some guidance because I can't find images tagged for olive either at `edxops` or `openedx` DockerHub profiles.
Some of them exist (e.g. [edxapp at edxops](https://hub.docker.com/r/edxops/edxapp/tags?page=1&name=olive)), but some are absent, e.g. [discovery at edxops](https://hub.docker.com/r/edxops/discovery/tags?page=1&name=olive), [credentials at edxops](https://hub.docker.com/r/edxops/credentials/tags?page=1&name=olive), [discovery at openedx](https://hub.docker.com/r/openedx/discovery/tags?page=1&name=olive), etc

**Comment by iamsobanjaved** [comment]
Opening this again, will verify that all images are created with the `olive` tag

**Comment by UsamaSadiq** [comment]
[edxapp:olive.master](https://hub.docker.com/r/edxops/edxapp/tags?page=1&name=olive) is available now. I'll investigate all the other services and test that the devstack works for olive branches of all services perfectly.

**Comment by UsamaSadiq** [comment]
All the jobs for creating devstack images with olive tag have been created but those are by default only triggered once there is a new commit in the `olive.master` branch in any service. That's why only `edxapp` image has been built till now. 
I'll ask the SRE team to trigger these jobs manually so every service will have an image with `olive.master` tag published as well.

**Comment by dyudyunov** [comment]
> All the jobs for creating devstack images with olive tag have been created but those are by default only triggered once there is a new commit in the `olive.master` branch in any service. That's why only `edxapp` image has been built till now. I'll ask the SRE team to trigger these jobs manually so every service will have an image with `olive.master` tag published as well.

Thanks for that!

**Comment by UsamaSadiq** [comment]
[openedx/discovery-dev](https://hub.docker.com/r/edxops/discovery-dev/tags?page=1&name=olive) docker image has also been published successfully for `olive.master` branch.

**Comment by UsamaSadiq** [comment]
We've reached out to the Ecommerce owning team for resolving the Jenkins job failure in the Ecommerce repo. Closing the current issue since [another one](https://github.com/edx/upgrades/issues/109) has been opened in the maintenance board to track the ecommerce issue.
