### ISSUE TITLE
[Bug]: deprecated e2e repo still included in devstack by default.

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx-unsupported/devstack#1090]
### A/C

* [x] e2e repo is no longer included in devstack in master - https://github.com/openedx/devstack/pull/1099
* [x] ...as well as in Palm (released just as we started working on this ticket) - https://github.com/openedx/devstack/pull/1102
* [ ] ~~...maybe also Olive, if it's easy - https://github.com/openedx/devstack/pull/1103~~

### Describe the bug that you are seeing.

We got a [bug report from the community](https://forum.opencraft.com/t/how-to-run-opencraft-for-development/1541) that setting up a devstack using `OPENEDX_RELEASE` set to `olive.master` or `olive.4` is not working for new installations of devstack:

```
# make dev.clone
The [ecommerce] repo is already checked out. Checking for updates.
Checking out branch open-release/olive.4
From https://github.com/openedx/ecommerce
 * tag                   open-release/olive.4 -> FETCH_HEAD
Already up to date.
Cloning into 'edx-e2e-tests'...
fatal: Remote branch open-release/olive.4 not found in upstream origin
make[1]: *** [Makefile:173: impl-dev.clone.ssh] Error 128
make[1]: Leaving directory '/home/zest/setup/programs/devstack-container/devstack'
Would you like to assist devstack development by sending anonymous usage metrics to edX? Run `make metrics-opt-in` to learn more!
make: *** [Makefile:176: dev.clone.ssh] Error 2
```

Since [e2e tests have been deprecated](https://discuss.openedx.org/t/deprecation-removal-edx-e2e-tests/9115) it seems like this repo and related functionality should be removed from devstack?

### Did this happen on the host (your machine or the remote instance) or in the container?

host

### Steps to reproduce.

1. Start with a fresh clone of `devstack` that has no repos or data.
2. Run `OPENEDX_RELEASE=olive.master make dev.clone`

You will see:

```
Cloning into 'edx-e2e-tests'...
fatal: Remote branch open-release/olive.master not found in upstream origin
```

### What system was this issue seen on?

Apple Silicon

**Comment by timmc-edx** [comment]
I've fixed this on master and have another PR to backport it to Palm (https://github.com/openedx/devstack/pull/1102) but I wasn't able to backport it to Olive (https://github.com/openedx/devstack/pull/1103) -- or at least, not without tests breaking. It's possible that our provisioning CI checks just don't work very well on named release branches.

I'm probably not going to pursue the Olive fix since Palm is now current and I'm leery of checking in changes that might have broken something else, but if someone wants to push it forward, there's at least a branch to start from.
